[base]
sql_file_path = './misc/sqlscript'
log_file_path = './volumes/logs'
security_hash_key = 'vataminstudio'

[console_logger]
level = "DEBUG"
format = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level> - [{elapsed}]"

[app_logger]
rotation = "00:00"
retention = "1 week"
level = "DEBUG"
format = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level> - [{elapsed}]"

[localdb]
database_type = 'sqlite'
database_path = './volumes/database'
database_name = 'vitamin.db'

[serverdb]
database_type = 'postgresql'
db_name = 'vunolblt_db'
host = 'localhost'
port = 15432
user = 'vunolbltmaster'
pwd = 'vn!vunolbltmaster##!'
schema = 'vunolblt'
