delete from base_cmn_cd;

insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B01', '-', '사용여부', null, 1, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B01', 'Y', '사용',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B01', 'N', '사용안함', null, 2, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B02', '-', '화면 표시 여부', null, 2, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B02', 'Y', '사용',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B02', 'N', '사용안함', null, 2, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B03', '-', '사용자 유형 코드', null, 3, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B03', '1', '일반',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('B03', '9', '관리자', null, 2, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S01', '-', '영문 단어 유형 코드', null, 4, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S01', '1', '단어',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S01', '2', '약어', null, 2, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S02', '-', '한글 단어 유형 코드', null, 5, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S02', '1', '단일어',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S02', '2', '합성어',    null,  2,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S02', '3', '접두어',    null,  3,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S02', '4', '접미어', null, 4, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S03', '-', '단어 구분 코드', null, 6, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S03', '1', '표준단어',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S03', '2', '동음이의어',    null,  2,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S03', '3', '금칙어',    null,  3,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '-', 'DBMS 유형 코드', null, 7, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '00', '공통',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '01', 'oracle',    null,  2,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '02', 'mssql',    null,  3,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '03', 'postgresql',    null,  4,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '04', 'mysql',    null,  5,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '05', 'mariadb',    null,  6,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '06', 'sqlite',    null,  7,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S04', '07', 'firebird',    null,  8,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S05', '-', '도메인 여부', null, 9, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S05', 'Y', '도메인',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S05', 'N', '도메인아님',    null,  2,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '001', 'VARCHAR',    null,  1,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '002', 'NVARCHAR',    null,  2,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '003', 'CHAR', null, 3, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '004', 'NCHAR',    null,  4,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '005', 'DATE',    null,  5,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '006', 'TIME', null, 6, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '007', 'DATETIME',    null,  7,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '008', 'TIMESTAMP',    null,  8,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '009', 'CLOB', null, 9, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '010', 'TEXT',    null,  10,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '011', 'BLOB',    null,  11,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '012', 'INTEGER', null, 12, 'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '013', 'INT',    null,  13,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '014', 'NUMBER',    null,  14,'Y', 'Y', datetime(), datetime());
insert into base_cmn_cd(key_cd, type_cd, cd_nm_1, cd_nm_2, sort_order, use_yn, dspy_yn, reg_dt, mdfy_dt) values ('S06', '015', 'NUMERIC', null, 15, 'Y', 'Y', datetime(), datetime());
